config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "locations#index"
  resources :locations, except: [:new, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :city_name, presence: true
  validates :city_id, presence: { message: "not found in our database. Please enter a city and state in this format: Dallas, TX" }

  SOCRATA_APP_TOKEN = Rails.application.secrets.socrata_app_token

  def get_city_id
    json = HTTParty.get("http://api.opendatanetwork.com/entity/v1?entity_name=#{URI.encode(self.city_name)}&app_token=#{SOCRATA_APP_TOKEN}")
    logger.debug { "city_id json: #{json}"}
    if json["entities"] && json["entities"].length > 0
      name_match = json["entities"].select { |record| record["name"] == self.city_name }
      if name_match.length > 0
        self.city_id = name_match[0]["id"]
      else
        logger.warn { "City ID response did not match city name: #{json["entities"]}"}
        nil
      end
    else
      logger.warn { "City ID response for #{self.city_name} contained no entities: #{json}" }
      nil
    end
  end

  def crime_data_url
    "https://api.opendatanetwork.com/data/v1/values?app_token=#{SOCRATA_APP_TOKEN}&variable=crime.fbi_ucr.rate&entity_id=#{self.city_id}&crime_type=All%20Crimes"
  end

  def earnings_data_url
    "https://api.opendatanetwork.com/data/v1/values?app_token=#{SOCRATA_APP_TOKEN}&variable=jobs.earnings.median_earnings&entity_id=#{self.city_id}"
  end

  def pop_change_data_url
    "https://api.opendatanetwork.com/data/v1/values?app_token=#{SOCRATA_APP_TOKEN}&variable=demographics.population.change&entity_id=#{self.city_id}"
  end

  def get_data(url)
    json = HTTParty.get(url)
    if json['error']
      json['error']['message']
    elsif json['data'].length > 0
      rows = json['data']
      rows.delete_at(0) # remove header row to enable sort
      most_recent = rows.max_by do |row|
        row[0]
      end
      most_recent[1]
    end
  end

  def self.to_csv
    attributes = %w{city_name crime_rate earnings}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |city|
        csv << city.attributes.values_at(*attributes)
      end
    end
  end

  def get_stats
    self.city_id = get_city_id
    self.crime_rate = get_data(crime_data_url)
    self.earnings = get_data(earnings_data_url)
    self.pop_change = get_data(pop_change_data_url)
  end
  before_validation :get_stats

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
    @location = Location.new

    respond_to do |format|
      format.html
      format.csv { send_data @locations.to_csv }
    end
  end

  def create
    @location = Location.new(strong_params)
    if @location.save
      flash[:success] = "Location created"
    else
      flash[:warning] = @location.errors.full_messages
    end
    redirect_to root_path
  end

  def destroy
    Location.find(params[:id]).destroy!
    redirect_to root_path
  end

  private
    def strong_params
      params.require(:location).permit(:city_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def join_messages(messages)
    messages = messages.join('; ') if messages.is_a? Array
    messages
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>City Stats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <%= content_tag(:div, join_messages(msg), class: "alert alert-#{type}") %>
    <% end %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>City Stats</h1>

<%= form_for @location do |form| %>
  <h2>Enter a city and state</h2>
  <%= form.text_field :city_name, placeholder: "Dallas, TX" %>
  <%= form.submit "Add city" %>
<% end %>

<h2>Locations <%= link_to "Download as CSV", locations_path(format: :csv), class: "btn btn-primary pull-right" %></h2>
<table class="table">
  <thead>
    <tr>
      <th>City</th>
      <th>Median Earnings</th>
      <th>Crime Rate <small>(annual crimes per 100k)</small></th>
      <th>Population Rate of Change</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.city_name %></td>
        <td><%= number_to_currency(location.earnings, precision: 0) %></td>
        <td><%= number_with_delimiter(location.crime_rate) %></td>
        <td><%= number_to_percentage(location.pop_change) %></td>
        <td><%= button_to "Delete", location_path(location), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>